DROP DATABASE IF EXISTS PRODUCTOS;
CREATE DATABASE PRODUCTOS;
USE PRODUCTOS;

CREATE TABLE ALMACEN (
    ID CHAR(4) PRIMARY KEY,
    ALMACEN_DE VARCHAR(40)
);

CREATE TABLE PRODUCTOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(40) NOT NULL,
    DESCRIPCION VARCHAR(80) NOT NULL,
    ALMACEN CHAR(4) NOT NULL,
    FOREIGN KEY (ALMACEN) REFERENCES ALMACEN(ID)
);